[package]
name = "rmk-config"
version = "0.1.0"
edition = "2021"
authors = ["Haobo Gu <haobogu@outlook.com>"]
description = "Keyboard firmware written in Rust"
homepage = "https://github.com/haobogu/rmk"
repository = "https://github.com/haobogu/rmk"
license = "MIT OR Apache-2.0"
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = { version = "1.0.0" }
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }

embassy-nrf = { version = "0.1.0", features = [
    "unstable-pac",
    "time",
], optional = true }

[features]
default = []
toml = ["serde", "serde_derive"]
_esp_ble = []
_nrf_ble = ["embassy-nrf"]
